reporting:
  print: summary
  reports:
    - lcovonly
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
check:
  global:
    statements: 0
    lines: 0
    branches: 0
    functions: 0
    excludes: []
  each:
    statements: 0
    lines: 0
    branches: 0
    functions: 0
    excludes: []
