version: 0.1
environment_variables:
  plaintext:
    FFPROBE_PATH: "bin/ffprobe"
    BUILD_PHASE_MARKER: build_phase_complete
phases:
  install:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
  pre_build:
    commands:
      - npm install
      - chmod +x get-ffmpeg
      - ./get-ffmpeg
  build:
    commands:
      - npm test
      - touch $BUILD_PHASE_MARKER
  post_build:
    commands:
      - test -e $BUILD_PHASE_MARKER
      - echo Zipping Lambda code
      - zip -r cms-audio-lambda-$(basename $CODEBUILD_SOURCE_VERSION) . -x .git
      - echo Copying zipped Lambda to S3 $CODE_BUCKET
      - aws s3 cp cms-audio-lambda-$(basename $CODEBUILD_SOURCE_VERSION) s3://$CODE_BUCKET/cms-audio-lambda-$(basename $CODEBUILD_SOURCE_VERSION)
      # TODO Get version ID and write it back to template config
artifacts:
  # It seems like CodePipeline and CodeBuild expect an artifact here. Currently
  # we don't need any, so this is essentially a no-op.
  files:
    - README.md
