version: 0.2
env:
  variables:
    PRX_LAMBDA_CODE_S3_KEY: "lambda/PRX-cms-audio-lambda.zip"
    PRX_LAMBDA_CODE_CONFIG_PARAMETERS: "CmsAudioLambdaCodeS3ObjectVersion"
    PRX_LAMBDA_ARCHIVE_BUILD_PATH: "/app/build.zip"
  parameter-store:
    CMS_ACCESS_KEY_ID: "/prx/test/cms-audio-lambda/AWS_ACCESS_KEY_ID"
    CMS_DEFAULT_REGION: "/prx/test/cms-audio-lambda/AWS_DEFAULT_REGION"
    CMS_SECRET_ACCESS_KEY: "/prx/test/cms-audio-lambda/AWS_SECRET_ACCESS_KEY"
phases:
  build:
    commands:
      - "cd $(ls -d */|head -n 1)"
      - "echo AWS_ACCESS_KEY_ID=$CMS_ACCESS_KEY_ID > .env"
      - "echo AWS_DEFAULT_REGION=$CMS_DEFAULT_REGION >> .env"
      - "echo AWS_SECRET_ACCESS_KEY=$CMS_SECRET_ACCESS_KEY >> .env"
      - "docker-compose build"
      - "docker-compose run test ci"
  post_build:
    commands:
      - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
